name: Nightly push test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittest:
    strategy:
      matrix:
        python-version: [3.7]
        platform: [ubuntu-18.04]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            README.md
